---
# This playbook will install stuff
#
- hosts: all
  remote_user: docker
  become: yes
  become_method: sudo
  tasks:
    - name: "Add Ondrej Apache2 repository"
      apt_repository:
        validate_certs: no
        repo: 'ppa:ondrej/apache2'
        state: present
    - name: "Add Ondrej PHP repository"
      apt_repository:
        validate_certs: no
        repo: 'ppa:ondrej/php'
        state: present
